- name: install nginx and run
  hosts: frontend
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.package:
    name: nginx
    state: present

  - name: start nginx
    ansible.builtin.debug:
    name: nginx
    state: started
    enabled: yes
