- name: install nginx and run 
  hosts: frontend
  connection: local 
  tasks: 
  - name: install nginx 
    ansible.builtin.package: 
       name: nginx 
       state: installed 
  - name: start nginx 
    ansible.builtin.service: 
        name: nginx 
        state: started 
        enabled: yes      