- name: install nginx nginx and run
  hosts: frontend
  become: yes
  tasks: 
  - name: install nginx
    ansible.builtin.package:
     name: nginx
     state: installed

  - name: start nginx
    ansible.builtin.service:
    state: start
    enable: yes   
