- name: play1 
  hosts: local 
  connection: local 
  tasks: 
  - name: hello from play1 and task1
    ansible.builtin.debug: 
      msg: "HeLLO PLAY1 AND TASK1"

  - name: hello from play1 and task2
    ansible.buitlin.debug:
      msg: "Hello from play1 and task2"    

- name: play2 
  hosts: local 
  connection: local 
  tasks: 
  - name: hello from play2 and task1
    ansible.builtin.debug:
      msg: "hello from play2 and task1"

  - name: hello from  play2 and task2 
    ansible.builtin.debug:
      msg: "hello from play2 and task2"    
