- name: play1 
  hosts: local 
  connection: local 
  tasks: 
  - name: hello from play1 and task1
    ansible.builtin.debug: 
      msg: "HELLO PLAY-1 AND TASK-1"

  - name: hello from play1 and task2 
    ansible.buitlin.debug:
      msg:  "HELLO FROM PLAY-1 AND TASK-2"

- name: play2 
  hosts: local 
  connection: local 
  tasks: 
  - name: hello from play2 and task1
    ansible.builtin.debug:
      msg: "HELLO FROM PLAY-2 AND TASK-1"

  - name: hello from  play2 and task2 
    ansible.builtin.debug:
      msg: "HELLO FROM PLAY-2 AND TASK-2"  
