- name: play1
  hosts: local 
  connection: local 
  tasks: 
  - name: print play1 and task1
    ansible.builtin.debug:
      msg: "Hello PLAY-1 AND TASK-1"

  - name: print play1 and task2
    ansible.builtin.debug:    
      msg: "Hello PLAY-1 AND TASK-2"

- name: play2
  hosts: local         
  connection: local 
  tasks: 
  - name: print play2 and task1
    ansible.builtin.debug: 
      msg: "Hello PLAY-2 AND TASK-1"

  - name: print play2 and task2 
    ansible.builtin.debug:
      msg: "Hello PLAY-2 AND TASK-2"   