- name: play level variables
  hosts: local
  connection: local
  vars:
   COURSE: ANSIBLE # equal to COURSE=ANSIBLE in shell, shell we refer $var or ${{var}}
   DURATION: 10HR
   TRAINER: Sivakumar
  tasks:
  - name: print course information
    ansible.builtin.debug:
    # vars reference should be surrounded by ""
     msg: "Hello {{ COURSE }}, Course Duration: {{ DURATION }}, Trainer: {{ TRAINER }}"    