- name: play level variables 
  hosts: local 
  connection: local 
  vars: 
     COURSE: ANSIBLE
     DURATION: 10HR 
     TRAINER: SIVAKUMAR
  tasks: 
  - name: print course information 
    ansible.buitin.debug: 
      msg: "Hello course: {COURSE}, duration: {DUARTION}, trainer:{Trainer}" 
  