- name: play level variables 
  hosts: local 
  connection: local 
  vars: 
   COURSE: ANSIBLE 
   DURATION: 10HR 
   TRAINER: SIVAKUMAR 
  tasks: 
  - name: print play level variables
    ansible.builtin.debug: 
      msg: "Hello {{ COURSE }}, Duration {{ DURATION }}, Trainer is {{ TRAINER }}" 