- name: play level variables
  hosts: local
  connection: local
  vars:
   COURSE: DevOps with Aws 
   DURATION: 10HR
   TRAINER: Sivakumar
  tasks:
  - name: print course information
    vars:
     COURSE: ANSIBLE
    ansible.builtin.debug:
    #vars reference should be surrounded by ""
     msg: "Hello {{ COURSE }}, Course Duration: {{ DURATION }}, Trainer is: {{ TRAINER }}"

  - name: print course information
    ansible.builtin.debug:
    # vars reference should be surrounded by ""
     msg: "Hello {{ COURSE }}, Course Duration: {{ DURATION }}, Trainer is: {{ TRAINER }}"