- name: task level vars 
  hosts: local 
  connection: local 
  vars: 
    COURSE: ANSIBLE 
    DURATION: 10HR 
    TRAINER: Sivakumar
  tasks: 
  - name: print course information
    vars: 
      COURSE: DEVOPS 
    ansible.builtin.debug: 
      mag: "Hello {{ COURSE }} Duration {{ DURATIO }} Trainer is {{ TRAINER }}"
      
        