- name: play level variables
  hosts: local
  connection: local
  vars:
   COURSE: DevSecops with Aws
   DURATION: 10HR
   TRAINER: Sivakumar
  tasks:
  - name: print course information
    vars:
     course: ansible
    ansible.builtin.debug:


  - name: print course information again
    ansible.builtin.debug:
     msg: "Hello {{ COURSE }}, Duration {{ DURATION }}, Trainer is{{ TRAINER }}"   