- name: variables form files 
  hosts: local 
  connection: local 
  vars_files: # we wont include here file this will throw a error ok 
  - course.yaml 
  tasks: 
  - name: print course information 
    ansible.builtin.debug: 
      msg: "Hello I am learning {{ COURSE }}, duration {{ DURATION }}, Trainer is {{ TRAINER }}" 