- name: variables from prompt 
  hosts: local 
  connection: local 
  vars_prompt: 
  - name: username 
    prompt: please enter your username 
    private: true 

  - name: psaaword 
    prompt: please enter your password 
    private: false 
  tasks: 
  - name: print user information 
    ansible.builtin.debug: 
      msg: "hello username is: {username} and password is: {password}"     