- name: vars from inventory 
  hosts: local 
  connection: local 
  tasks: 
  - name: print course information 
    ansible.builtin.debug: 
      mag: "Hello {{ COURSE }}, Duration {{ DURATION }}, Trainer is: {{ TRAINER }}"
     