- name: variables from inventory 
  hosts: frontend 
  connection: local 
  tasks: 
  - name: print course information 
    ansible.buitin.debug: 
      msg: "Hello {{ COURSE }}, Duratio {{ DURATION }}, Trainer is {{ TRAINER }}"