- name: variables from inventory 
  hosts: frontend 
  tasks: 
  - name: print course information 
    ansible.buitin.debug: 
      msg: "Hello i am learning  {{ COURSE }}, Duratio {{ DURATION }}, Trainer is {{ TRAINER }}"