- name: vars from args 
  hosts: local 
  connection: local 
  tasks: 
  - name: print course informaton 
    ansible.builtin.debug: 
      msg: "Hello i am learning {{ COURSE }}, Duration {{ DURATION }}, Trainer is {{ TRAINER }}"