- name: variables from inventory
  hosts: locsal
  connection: local
  tasks: 
  - name: print user information
    ansible.builtin.debug:
     msg: "Hello course information {{ COURSE }}, Duration {{ DURATION }}, Trainer is {{ TRAINER }}"