- name: understand vars preference
  hosts: local
  connection: local
  # vars:
  #  GREETING: "Hello from Play"
  # vars_files: 
  # - course.yaml
  # vars_prompt:
  #  - name: GREETING
  #    prompt: hello from prompt
  #    private: false
  tasks:
  - name: print the GREETING  
    # vars:
    #  GREETING: "Hello from Task" 
    ansible.builtin.debug:
     msg: "{{ GREETING }}"  
  
  