 - name: data types
   hosts: local
   connection: local
   vars:
    COURSE: DevSecOps with Aws 
    DURATION: 120HR
    IS_LIVE: true 
    TOOLS:
    - linux
    - shell
    - zip
    CONCEPTS:
     CI: Jenkins
     SCRIPTING: shell,python.terraform,ansible
   tasks:
   - name: print course information
     ansible.builtin.debug:
      msg: "Hello {{ COURSE }}, Duration {{ DURATION }}, Trainer is {{ TRAINER }}, is live? {{ IS_LIVE }}"    