- name: ansible datatypes
  hosts: local 
  connection: local
  vars:
   DURATION: 120 # this is number
   COURSE: DevSecOps with Aws #object
   IS_LIVE: true  #boolean
   TOOLS: #list
   - linux
   - shell
   - ansible
   CONCEPTS: # map or object or dictionary {}
    CI: Jenkins
    SCRIPTING: Shell,ansible,terraform,python
  tasks:
  - name: print course information
    ansible.builtin.debug:
     msg: "course is: {{ COURSE }}, Duration: {{ DURATION }}, IS LIVE? {{ IS_LIVE }}, Tools: {{ TOOLS }}, Concepts are: {{ CONCEPTS }}" 
