- name: data types 
  hosts: local 
  connection: local 
  vars: 
   COURSE: DEVSECOPS WITH AWS
   DURATION: 120HR 
   TRAINER: SIVA 
   IS_LIVE: TRUE 
   TOOLS: #LIST 
   - linux 
   - shell
   - nginx 
   CONCEPTS: 
     CI: Jenkins 
     SCRIPTING: Shell,Ansible,Terraform,Python 
  tasks: 
  - name: print course information 
    ansible.builtin.debug: 
      msg: "Hello {{ COURSE }},duration {{ DURATION }}, Trainer is {{ TRAINER }}, is_live?:{{ IS_LIVE }},Concepts are:{{ CONCEPTS }}"   