- name: ansible datatypes 
  hosts: local 
  connection: local 
  vars: 
    COURSE: "DEVSECOPS WITH AWS" #STRING 
    DURATION: 120HR #NUMBER 
    TRAINER: SIVAKUMAR
    IS_LIVE: True #boolean 
    TOOLS: #LIST 
    - linux 
    - ansible 
    - shell
    CONCEPTS: #map or object or dict {}
      CI: Jenkins 
      Scripting: Shell,Ansible,Terraform,Python 
  tasks: 
  - name: print the datatypes information     
    ansible.builtin.debug: 
      msg: "Hello, course is: {COURSE}, duration: {DURATION},trainer is: {TRAINER}, is live?: {IS_LIVE},tools are: {TOOLS},concepts are: {CONCEPTS}"