- name: data types
  connection: local
  hosts: local 
  vars: 
   COURSE: subbu
   DURATION: 120HR 
   TRAINER: Sivakumar
   IS_LIVE: true
   TOOLS:
   - mysql
   - shell
   - ansible 
   CONCEPTS:
     CI: Jenkins
     SCRIPTING: shell,python,ansible,ansible 
  tasks: 
  - name: print course information 
    ansible.builtin.debug: 
     msg: "Hello {{ COURSE }} Duration {{ DURATION }} Trainer is {{ TRAINER }} Is_live ?{{ IS_LIVE }} Tools are: {{ TOOLS }} scripting are {{ SCRIPTING }}"   