- name: ansible datatypes 
  hosts: local 
  connection: local 
  vars:
   COURSE: ANSIBLE 
   DURATION: 120 HR 
   TRAINER: Sivakumar
   Tools:
   - linux 
   - ansible
   - shell 
   IS_LIVE: true 
   CONCEPTS: 
     CI: Jenkins 
     SCRIPTING: shell,ansible,terraform,python 
  tasks: 
  - name: print the course information 
    ansible.builtin.debug: 
      msg: "Hello {{ COURSE }}, Duration {{ DURATION }} IS_LIVE? {{ IS_LIVE }}, Trainer is {{ TRAINER }},CONCEPTS {{ CONCEPTS }}"    