- name: conditions demo 
  hosts: local
  commection: local
  vars: 
    NUMBER: 78
  tasks: 
  - name: print given munber is less than or equal to 100
    ansible.builtin.debug:
     msg: "Given Number {{ NUMBER }} is less than or equal to 100"
    when: NUMBER < = 100

  - name: print given number is greater than 100
    ansible.builtin.debug: 
     msg: "Given Number {{ NUMBER }} is greater than 100"
    when: NUMBER > 100      