- name: playbook control using ansible facts
  hosts: frontend
  become: yes
  tasks: 
  - name: install nginx if redhat
    ansible.builtin.dnf:
      name: nginx
      state: present
    when: OS_family == "RedHat"

  - name: install nginx if debian
    ansible.builtin.dnf:    
      name: nginx
      state: present
    when: OS_family == "Debian"
