- name: install packages 
  hosts: frontend 
  become: yes 
  tasks: 
  - name: install packages 
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: installed 
    loop:
    - mysql 
    - nginx
    - zip  

   