- name: install packages 
  hosts: frontend 
  become: yes 
  tasks: 
  - name: install the packages 
    ansible.builtin.dnf: 
       name: "{{ item }}" 
       state: installed 
    loop: 
    - nginx 
    - mysql 
    - zip    