- name: install packages
  hosts: frontend
  become: yes 
  tasks:
  - name: install packages
    ansible.builtin.package:
      name: "{{ item.item }}"
      state: "{{ item.state }}"

    loop:
    - { name: 'nginx', state: 'installed' }
    - { name: 'mysql', state: 'absent'}
    - { name: 'zip', state: 'absent' }
    