- name: install packages 
  hosts: frontend 
  become: yes 
  tasks: 
  - name: install packages 
    ansible.builtin.dnf: 
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop:
    - { item: 'nginx', state: 'present' }
    - { item: 'mysql', state: 'present' }
    - { item: 'zip', state: 'absent' }
