- name: fuctions
  hosts: local
  connection: local
  vars: 
    persons: "Ramesh,Arun,Supriya,Ajay"
  tasks: 
  - name: check the  undefined variable
    ansible.builtin.debug:
     msg: "Hello, {{ person | default ('Arun') }}" 

  - name: print names
    ansible.builtin.debug:
     msg: "Hello, {{ persons | split (',') }}"

  - name: convert map into list 
    vars:
     COURSE:
       name: ansible
       duration: 10HR
       trainer: Sivakumar
    ansible.builtin.debug:
     msg: "Hello , {{ COURSE | dict2items }}"

  - name: convert list into map
    vars:
      course:
       - {'key': 'name', 'value': 'ansible'}
       - {'key': 'duration', 'value': '10HR'}
       - {'key': 'trainer', 'value': 'Sivakumar'}
    ansible.builtin.debug:
     msg: "Hello {{ course | items2dict }}"

