- name: fuctions
  hosts: local
  connection: local
  vars: 
    persons: "Ramesh,Arun,Supriya,Ajay"
  tasks: 
  - name: check the  undefined variable
    ansible.builtin.debug:
     msg: "Hello, {{ person | default ('Arun') }}" 

  - name: print names
    ansible.builtin.debug:
     msg: "Hello, {{ persons | split (',') }}"

  - name: convert map into list 
    vars:
     COURSE:
       name: ansible
       duration: 10HR
       trainer: Sivakumar
    ansible.builtin.debug:
     msg: "Hello , {{ COURSE | dict2items }}"      
