- name: functions
  hosts: local 
  connection: local
  vars: 
    persons: "ramesh,arun,ajay,supriya"
  tasks:
  - name: check undefined variable
    ansible.builtin.debug:
     msg: "{{ person | default ('Ramesh') }}"

  - name: print names
    ansible.builtin.debug:
     msg: "Hello {{ persons | split (',') }}"

  - name: convert map into list 
    vars:
     course:
      name: ansible
      duration: 120HR
      trainer: Sivakumar
    ansible.builtin.debug:
     msg: "Course Info: {{ course | dict2items }}"
      

  - name: convert list to map 
    vars:
     course:
     - {'key': 'name', 'value': 'ansible'}
     - {'key': 'duration', 'value': '120HR'}
     - {'key': 'trainer', 'value': 'Sivakumar'}
    ansible.builtin.debug:
     msg: "Course Info: {{ course | items2dict }}"      


