- name: functions
  hosts: local
  connection: local
  vars: 
   persons: "ramesh,raju,arun,supriya"
  tasks:
  - name: check undefined variable 
    ansible.builtin.debug:
     msg: "Hello, {{ person | default ('ramesh') }}"

- name: print names
  ansible.builtin.debug:
   msg: "Hello {{ persons | split (',') }}"