- name: functions
  hosts: local
  connection: local
  vars:
   persons: "Ramesh,subbu,tarak,sitara"
  tasks:
  - name: check undefined variable
    ansible.builtin.debug:
     msg: "Hello {{ person | default ('subbu') }}"

  - name: print names   
    ansible.builtin.debug:
     msg: "Hello {{ persons | split(',') }}"

  - names: convert map into list
    vars:
     course:
       name: ansible
       duration: 10hr
       trainer: sivakumar
    ansible.builtin.debug:
     msg: "course info  {{ course | dict2item }}"      