 - name: functions
   hosts: local
   connection: local
   vars:
     persons: "ramesh,raju,seenu,siva"
   tasks:
   - name: check undefined variables
     ansible.builtin.debug:
      msg: "{{ person | default ('ramesh') }}" 

   - name: print names
     ansible.builtin.debug:
      msg: "{{ persons }}"

   - name: convert map into list
     vars:
       COURSE: ansible
       DURATION: 10HR
       TRAINER: Sivakumar
     ansible.builtin.debug:
       msg: "course info: {{ COURSE | dict2items }}"       
