- name: functions
  hosts: local
  connection: local
  vars:
   persons: "Ramesh,subbu,ganga,seeta"
  tasks: 
  - name: check undefined variable
    ansible.builtin.debug:
     msg: "Hello {{ person | default ('Ramesh') }}"

  - name: print names
    ansible.builtin.debug:
     msg: "Hello {{ persons | split(',') }}"   

  - name: convert map into list
    vars:
     course:
      name: ansible
      duration: 10HR
      trainer: Sivakumar
    ansible.builtin.debug:
     msg: "Course Info: {{ course | dict2items }}"  

  - name: convert list into map
    vars:
      course:
      - {'key': 'name', 'value': 'ansible'}
      - {'key': 'duration', 'value': '10HR'}
      - {'key': 'trainer', 'value': 'Sivakumar'}
    ansible.builtin.debug:
     msg: "Course Info : {{ course | items2dict }}"  

  - name: convert into upercase
    vars:
     name: sivakumaR Redddy map
    ansible.builtin.debug:
     msg: "{{ name | upper }}"    
   
  - name: convert into lowercase
    vars:
     name: SIVAKUMAR REDDY map
    ansible.builtin.debug:
     msg: "{{ name | lowercase }}"
       
