- name: functions 
  hosts: local
  connection: local 
  vars: 
    persons: "ramesh,suresh,seets,rama"
  tasks: 
  - name: check undefined variable 
    ansible.builtin.debug: 
      msg: "{{ person | default ('ramesh') }}"

  - name: print names 
    ansible.builtin.debug: 
      msg: "{{ persons | split (',') }}"   

  - name: convert map to list 
    vars: 
     course: 
       name: ansible 
       duration: 10hr 
       trainer: sivakumar 
    ansible.builtin.debug: 
     msg: "hello {{ course | dict2items }}"

  - name: convert  list into map
    vars: 
    - {}      


