- name: functions
  hosts: local 
  connection: local 
  vars:
    persons: "ramesh,suresh,bharath,srinu"
  tasks:
  - name: check undefined variable 
    ansible.builtin.debug:
       msg: "{{ person | default ('ramesh') }}"

  - name: print names
    ansible.builtin.debug:
      msg: "Hello {{ persons |split (',') }}"

  - name: convert map into list 
    vars: 
      COURSE:
       name: ansible
       duration: 10hr 
       trainer: sivakumar 
    ansible.builtin.debug:
      msg: "{{ COURSE | dict2items }}"       