- name: functions
  hosts: local
  connection: local
  vars:
   persons: "ramesh,suresh,raheem,joseph"
  tasks: 
  - name: check undefined variable
    ansible.builtin.debug:
     msg: "{{ person | default ('Ramesh') }}"

  - name: print names
    ansible.builtin.debug:
     msg: "{{ person }}"   