- name: functions
  hosts: local
  connection: local
  vars:
   persons: "Ramesh,subbu,ganga,seeta"
  tasks: 
  - name: check undefined variable
    ansible.builtin.debug:
     msg: "Hello {{ person | default ('Ramesh') }}"

  - name: print names
    ansible.builtin.debug:
     msg: "Hello {{ persons }}"   

  - name: convet map into list
    vars:
     couse:
      name: ansible
      duration: 10 120HR
      trainer: Sivakumar
    ansible.builtin.debug:
     msg: "Course Info: {{ course | dict2items }}"  
