 - name: functions
   hosts: local
   connection: local
   vars:
     persons: "ramesh,raju,seenu,siva"
   tasks:
   - name: check undefined variables
     ansible.builtin.debug:
      msg: "{{ person | default ('ramesh') }}" 

   - name: print names
     ansible.builtin.debug:
      msg: "{{ persons }}"

   - name: convert map into lists
     vars:
       COURSE: ANSIBLE
       DURATION: 120HR
       TRAINER: Sivakumar
     ansible.builtin.debug:
       msg: "Hello course info {{ COURSE | dict2items }}"               
