- name: functions 
  hosts: local 
  connection: local 
  vars: 
   persons: "subbu,chinna,arun,tharun"
  tasks: 
  - name: check undefined variable 
    ansible.builtin.debug: 
      msg: "Hello, {{ person | default ('ramesh') }}"

  - name: print names 
    ansible.builtin.debug: 
      msg: "Hello {{ persons | split (',') }}"
  
  - name: convert map into list 
    vars: 
      course: 
        name: ansible 
        duration: 10hr 
        trainer: siva 
    ansible.builtin.debug: 
      msg: "{{ course | dict2items }}"
  
  - name: convert list into map 
    vars: 
      courses: 
         - { 'key': 'name','value': 'ansible'}
         - { 'key': 'duration','value': '10hr'}
         - { 'key': 'trainer','value': 'siva'} 
    ansible.builtin.debug: 
      msg: "{{ courses | items2dict }}"

  - name: convert to uppercase
    vars: 
      name: "subbu" 
    ansible.builtin.debug: 
      msg: "{{ name | upper }}"  
      