- name: functions
  hosts: local
  connections: local
  vars:
   person: "ramesh,suresh,subbu,tarak"
  tasks:
  - name: check undefined variable
    ansible.builtin.debug:
     msg: "Hello {{ person | default ('Ramesh') }}"

  - name: person names  
    ansible.builtin.debug:
     msg: {{ Person }} 