- name: shell vs command 
  hosts: frontend 
  become: yes 
  tasks: 
  - name: redirect output to a file 
    #ansible.builtin.command: "ls -ltr > /tmp/output.txt" 
    ansible.builtin.shell: "ls -ltr > /tmp/output.txt"