- name: shell vs command 
  hosts: frontend 
  become: yes 
  tasks: 
  - name: redirect to output to a file
    ansible.builtin.shell: "ls -ltr > /tmp/output.log"     
    #ansible.builtin.command: "ls -ltr > /tmp/output.log"
    register: command_result 

  - name: print command result 
    ansible.builtin.debug: 
     msg: "{{ command_result }}"  
                                                             