- name: shell v/s command 
  hosts: frontend 
  connection: local
  tasks: 
  - name: redirect to a file 
    #ansible.builtin.command: "ls -ltr > /tmp/anssible.txt"
    ansible.builtin.shell: "ls -ltr > /tmp/anssible.txt"