- name: shell vs command 
  hosts: frontend 
  become: yes 
  tasks: 
  - name: redirect output to a file 
    ansible.builtin.command: "ls -ltr" 
    register: command_result  

  - name: print command output  
    ansible.builtin.debug: 
      msg: "{{ command_result }}"  