- name: shell vs command 
  hosts: frontend 
  become: yes 
  tasks: 
  - name: redirect to output to a file
    ansible.builtin.command: "ls -ltr > /tmp/output.log"                                                                