- name: shell vs command
  hosts: local
  connection: local
  tasks:
  - name: redirect output to a file
    #ansible.builtin.command: "ls -ltr > /tmp/output.txt"
    ansible.builtin.command: "ls -ltr > /tmp/output.txt"
      
