- name: user creation
  hosts: local
  connection: local
  become: yes
  tasks: 
  - name: check roboshop user exist or not
    ansible.builtin.command: id roboshop
    registe: output 
    ignore_errors: true 

- name: create user
  ansible.builtin.command: useradd roboshop  
  when: output.stdout ! = 0

- name: user already exists
  ansible.builtin.debug:
    msg: "user already exists"
  when: output.stdout == 0    
