- name: user creation 
  hosts: local
  connection: local
  tasks: 
  - name: check user already exists or not 
    ansible.builtin.command: id roboshop
    register: output 
    ignore_error: true 
       