- name: create ec2 and r53 
  hosts: local 
  connection: local 
  vars: 
    instances:
    - mysql 
    - backend 
    - frontend 
  tasks: 
  - name: create ec2 
    amazon.aws.ec2_instance:
       name: "{{ item }}"
       security_group: "{{ sg_id }}"
       image_id: "ami-09c813fb71547fc4f"
       vpc_subnet_id: "{{ subnet_id }}"
       instance_type: "t3.micro"
       tags: 
         Name: "{{ item }}"
    loop: "{{ instances }}"
    register: ec2_output 

  - name: print ec2_output 
    ansible.builtin.debug: 
      msg: "{{ ec2_output }}"          