- name: create ec2 and route53 
  hosts: local 
  connection: local 
  vars: 
    instances:  
    - mysql 
    - backend
    - frontend 
    subnet_id: subnet-0bb6a6110e9180b91
    sg_id: sg-0ad4f1d9859b4f090
    zone: subbuaws.site 
  tasks: 
  - name: create ec2 
    amazon.aws.ec2_instance: 
      name: "{{ item }}" 
      vpc_subnet_id: "{{ subnet_id }}"
      security_group: "{{ sg_id }}" 
      instance_type: t2.micro 
      tags: 
        name: "{{ item }}" 
    loop: "{{ instances }}"  
    register: ec2.output 

  - name: print ec2 output 
    ansible.builtin.debug: 
      msg: "{{ec2.output }}" 

  - name: create route53 
    amazon.aws_route53: 
      state: present 
      zone: "{{ zone }}" 
      record: "{{ item.item }}.{{ zone }}" 
      value: "{{ value.instances[0].private_ip_address }}" 
      ttl: 1
      type: A 
      wait: true 
      overwrite: true 
    loop: "{{ ec2.output.results }}" 

         
  - name: create route53 
    amazon.aws_route53: 
      state: present 
      zone: "{{ zone }}" 
      record: "{{ zone }}"
      value: "{{ value.instances[0].private_ip_address }}" 
      ttl: 1
      type: A 
      wait: true 
      overwrite: true 
    loop: "{{ ec2.output.results }}" 
    when: item.item == frontend 