- name: create ec2 and r53 records
  hosts: local
  connection: local
  vars: 
   instances:
   - mysql
   - backend
   - frontend
   subnet_id: subnet-0d38aa51f4166a628
   sg_id: sg-04f5b8fdb267df1bd
  tasks:
  - name: create ec2
    amazon.aws.aws_ec2:
      name: "{{ item }}"
      vpc_subnet_id: "{{ subnet_id }}"
      instance_type: t3.micro
      security_group: "{{ sg_id }}"
      image_id: ami-09c813fb71547fc4f
      tags:
        Name: "{{ item }}"
    loop: "{{ instances }}"    