- name: create ec2 and route53 
  hosts: local 
  connection: local 
  vars: 
    instances:  
    - mysqllll  # ansible is poor in stste management it creates another one when we do changes it wont do editing of same that one that is reason 
    - backend
    - frontend 
    subnet_id: subnet-0bb6a6110e9180b91
    sg_id: sg-0ad4f1d9859b4f090
    zone: subbuaws.site 
  tasks: 
  - name: create ec2 
    amazon.aws.ec2_instance: 
      name: "{{ item }}" 
      vpc_subnet_id: "{{ subnet_id }}"
      security_group: "{{ sg_id }}" 
      image_id: ami-09c813fb71547fc4f
      instance_type: t2.micro 
      tags: 
        name: "{{ item }}" 
    loop: "{{ instances }}"  
    register: ec2_output 

  - name: print ec2_output 
    ansible.builtin.debug: 
      msg: "{{ec2_output }}" 

  - name: create r53 records 
    amazon.aws.route53: 
      state: present 
      zone: "{{ zone }}" 
      record: "{{ item.item }}.{{ zone }}" 
      value: "{{ item.instances[0].private_ip_address }}" 
      ttl: 1
      type: A 
      wait: true 
      overwrite: true 
    loop: "{{ ec2_output.results }}" 

         
  - name: create r53 records
    amazon.aws.route53: 
      state: present 
      zone: "{{ zone }}" 
      record: "{{ item.item }}.{{ zone }}"
      value: "{{ item.instances[0].public_ip_address }}" 
      ttl: 1
      type: A 
      wait: true 
      overwrite: true 
    loop: "{{ ec2_output.results }}" 
    when: item.item == frontend 