- name: create ec2 and r53 reords 
  hosts: local 
  connection: local 
  vars: 
    instances: 
    - mysql
    - backend
    - frontend 

  tasks: 
  - name: create ec2 
    amazon.aws.ec2_instance: 
       name: "{{ item }}" 
       vpc_subnet_id: "{{ subnet_id }}"
       security_group: "{{ sg_id }}"
       instance_type: "t3.micro"
       image_id: ""
       tags: 
         Name: "{{ item }}"
    loop: "{{ instances }}" 
    register: ec2_output

  - name: print ec2_ouutput 
    ansible.builtin.debug: 
      msg: "{{ ec2_output.results }}" 

  - name: create route53 records 
    ansible.builtin.route53:
      state: presen
      zone: "{{ zone }}" 
      type: "A"
      ttl: 1 
      record: "{{ item.item }}.{{ zone }}" 
      value: "{{ item.instances[0].private_ip-address }}" 
      wait: true 
      overwrite: true 
    loop: "{{ec2_output.results }}" 

  - name: create route53 records 
    ansible.builtin.route53:
      state: present 
      zone: "{{ zone }}" 
      type: "A" 
      ttl: 1 
      record: "{{ zone }}" 
      value: "{{ item.instances[0].public_ip_address }}" 
      wait: true 
      overwrite: true 
    loop: "{{ ec2_output.results }}" 
    when: item.item == "frontend" 
